
// auth
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

// signup
export const REGISTER_REQUEST = 'USERS_REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'USERS_REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'USERS_REGISTER_FAILURE';

//books
export const FETCH_BOOKS_BEGIN = "FETCH_BOOKS_BEGIN";
export const FETCH_BOOKS_SUCCESS = "FETCH_BOOKS_SUCCESS";
export const FETCH_BOOKS_FAILURE = "FETCH_BOOKS_FAILURE";
export const SEARCH_BOOK = 'SEARCH';

export const FETCH_BOOK_BEGIN = "FETCH_BOOK_BEGIN";
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS";
export const FETCH_BOOK_FAILURE = "FETCH_BOOK_FAILURE";

//mybooks
export const FETCH_MYBOOKS_BEGIN = "FETCH_MYBOOKS_BEGIN";
export const FETCH_MYBOOKS_SUCCESS = "FETCH_MYBOOKS_SUCCESS";
export const FETCH_MYBOOKS_FAILURE = "FETCH_MYBOOKS_FAILURE";

export const FETCH_READING_BEGIN = "FETCH_READING_BEGIN";
export const FETCH_READING_SUCCESS = "FETCH_READING_SUCCESS";
export const FETCH_READING_FAILURE = "FETCH_READING_FAILURE";

export const SET_READING_STATUS = "SET_READING_STATUS";
export const REMOVE_READING = "REMOVE_READING";
export const ADD_READING = "ADD_READING";

//notes
export const FETCH_NOTES_BEGIN = "FETCH_NOTES_BEGIN";
export const FETCH_NOTES_SUCCESS = "FETCH_NOTES_SUCCESS";
export const FETCH_NOTES_FAILURE = "FETCH_NOTES_FAILURE";

export const CHANGE_NOTE_TITLE = "CHANGE_NOTE_TITLE";
export const CHANGE_NOTE_NOTE = "CHANGE_NOTE_NOTE";
export const CHANGE_NOTE_BOOK = "CHANGE_NOTE_BOOK";
export const CHANGE_NOTE_PAGE = "CHANGE_NOTE_PAGE";
export const CHANGE_NOTE_LABEL = "CHANGE_NOTE_LABEL";
export const CHANGE_ADDFORM_STATUS = "CHANGE_ADDFORM_STATUS";

export const ADD_NOTE = "ADD_NOTE";
export const REMOVE_NOTE = "REMOVE_NOTE";
export const FETCH_NOTES_BOOK = "FETCH_NOTES_BOOK";

//sentences
export const FETCH_SENTENCES_BEGIN = "FETCH_SENTENCES_BEGIN";
export const FETCH_SENTENCES_SUCCESS = "FETCH_SENTENCES_SUCCESS";
export const FETCH_SENTENCES_FAILURE = "FETCH_SENTENCES_FAILURE";

export const CHANGE_SENTENCE_TITLE = "CHANGE_SENTENCE_TITLE";
export const CHANGE_SENTENCE_SENTENCE = "CHANGE_SENTENCE_SENTENCE";
export const CHANGE_SENTENCE_BOOK = "CHANGE_SENTENCE_BOOK";
export const CHANGE_SENTENCE_PAGE = "CHANGE_SENTENCE_PAGE";
export const CHANGE_SENTENCE_LABEL = "CHANGE_SENTENCE_LABEL";
export const CHANGE_SENTENCE_ADDFORM_STATUS = "CHANGE_SENTENCE_ADDFORM_STATUS";

export const ADD_SENTENCE = "ADD_SENTENCE";
export const REMOVE_SENTENCE = "REMOVE_SENTENCE";
export const FETCH_SENTENCES_BOOK = "FETCH_SENTENCES_BOOK";

//userReadings
export const FETCH_USERREADINGS_BEGIN = "FETCH_USERREADINGS_BEGIN";
export const FETCH_USERREADINGS_SUCCESS = "FETCH_USERREADINGS_SUCCESS";
export const FETCH_USERREADINGS_FAILURE = "FETCH_USERREADINGS_FAILURE";

export const CHANGE_USERREADING_BOOK = "CHANGE_USERREADING_BOOK";
export const CHANGE_USERREADING_PAGE = "CHANGE_USERREADING_PAGE";
export const CHANGE_USERREADING_ADDFORM_STATUS = "CHANGE_USERREADING_ADDFORM_STATUS";

export const ADD_USERREADING = "ADD_USERREADING";
export const REMOVE_USERREADING = "REMOVE_USERREADING";
export const FETCH_USERREADINGS_BOOK = "FETCH_USERREADINGS_BOOK";

//targets
export const FETCH_TARGETS_BEGIN = "FETCH_TARGETS_BEGIN";
export const FETCH_TARGETS_SUCCESS = "FETCH_TARGETS_SUCCESS";
export const FETCH_TARGETS_FAILURE = "FETCH_TARGETS_FAILURE";

export const CHANGE_TARGET_BOOKCNT = "CHANGE_TARGET_BOOKCNT";
export const CHANGE_TARGET_STARTDATE = "CHANGE_TARGET_STARTDATE";
export const CHANGE_TARGET_FINISHDATE = "CHANGE_TARGET_FINISHDATE";
export const CHANGE_TARGET_PAGE = "CHANGE_TARGET_PAGE";

export const ADD_TARGET = "ADD_TARGET";
export const REMOVE_TARGET = "REMOVE_TARGET";

//home
export const FETCH_HOME_BEGIN = "FETCH_HOME_BEGIN";
export const FETCH_HOME_SUCCESS = "FETCH_HOME_SUCCESS";
export const FETCH_HOME_FAILURE = "FETCH_HOME_FAILURE";